Repository GreenyHat/Java-School, pull requests merged in 2023-10, with the labels that each got.

#5 Tema1ClaseFile-added
  ApuntesConCodigo/src/POO/FlujosDeDatos/Tema1ClaseFile.java
  ApuntesConCodigo/src/Testing/testingFlujos/test3.txt
Labels: hacktoberfest-acepted

#6 Update README.md
  README.md
Labels: documentation, help wanted, hacktoberfest-acepted

#7 Update README.md
  ApuntesConCodigo/README.md
Labels: documentation, help wanted, hacktoberfest-acepted

#9 Añadido tutorial JavaFX SceneBuilder
  sceneBuilderParaJAvaFx.md
Labels: documentation, question, hacktoberfest-acepted

#11 Create .gitattributes
  .gitattributes
Labels: bug, hotfix
